/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crearn;

import javax.swing.ImageIcon;

/**
 *
 * @author JORGE
 */
public class CalNum extends javax.swing.JFrame {

    /**
     * Creates new form CalNum
     */
    String num;
    public CalNum() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../images/icono.jpg")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Agency FB", 3, 10)); // NOI18N
        setForeground(new java.awt.Color(255, 153, 51));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.POPUP);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(114, 114, 30, 16);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(154, 114, 30, 16);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 114, 30, 16);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(248, 114, 30, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(67, 181, 134, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(207, 181, 134, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(67, 207, 134, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(207, 207, 134, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(67, 238, 134, 20);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(207, 238, 134, 20);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(67, 264, 134, 20);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(207, 264, 134, 20);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(67, 295, 134, 20);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(207, 295, 134, 20);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(67, 326, 134, 20);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(207, 326, 134, 20);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(67, 357, 134, 20);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(207, 357, 134, 20);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(67, 383, 134, 20);
        getContentPane().add(jTextField20);
        jTextField20.setBounds(207, 383, 134, 20);
        getContentPane().add(jTextField21);
        jTextField21.setBounds(67, 414, 134, 20);
        getContentPane().add(jTextField22);
        jTextField22.setBounds(207, 414, 134, 20);
        getContentPane().add(jTextField23);
        jTextField23.setBounds(67, 445, 134, 20);
        getContentPane().add(jTextField24);
        jTextField24.setBounds(207, 445, 134, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Ingresar Números");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(149, 78, 118, 25);

        jButton1.setText("Generar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(164, 145, 80, 17);
        getContentPane().add(jTextField25);
        jTextField25.setBounds(67, 476, 134, 20);
        getContentPane().add(jTextField26);
        jTextField26.setBounds(207, 476, 134, 20);
        getContentPane().add(jTextField27);
        jTextField27.setBounds(67, 507, 134, 20);
        getContentPane().add(jTextField28);
        jTextField28.setBounds(207, 507, 134, 20);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("número probable");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 20, 250, 50);

        setBounds(0, 0, 418, 582);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1.getText();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int captura1=0;
        int captura2=0;
        int captura3=0;
        int captura4=0;
        
    captura1=Integer.parseInt(this.jTextField1.getText());
    captura2=Integer.parseInt(this.jTextField2.getText());
    captura3=Integer.parseInt(this.jTextField3.getText());
    captura4=Integer.parseInt(this.jTextField4.getText());
    //int captura5=captura1+captura2+captura3+captura4;
      jTextField5.setText(String.valueOf(captura1+" "+ captura2+" "+ captura3+" "+ captura4));
      jTextField6.setText(String.valueOf(captura4+" "+ captura3+" "+ captura2+" "+ captura1));
      jTextField7.setText(String.valueOf(captura1+" "+ captura2+" "+ captura4+" "+ captura3));
      jTextField8.setText(String.valueOf(captura4+" "+ captura3+" "+ captura1+" "+ captura2));
      jTextField9.setText(String.valueOf(captura1+" "+ captura3+" "+ captura2+" "+ captura4));
      jTextField10.setText(String.valueOf(captura4+" "+ captura2+" "+ captura3+" "+ captura1));
      jTextField11.setText(String.valueOf(captura1+" "+ captura3+" "+ captura4+" "+ captura2));
      jTextField12.setText(String.valueOf(captura4+" "+ captura2+" "+ captura1+" "+ captura3));
      jTextField13.setText(String.valueOf(captura1+" "+ captura4+" "+ captura2+" "+ captura3));
      jTextField14.setText(String.valueOf(captura4+" "+ captura1+" "+ captura3+" "+ captura2));
      jTextField15.setText(String.valueOf(captura1+" "+ captura4+" "+ captura3+" "+ captura2));
      jTextField16.setText(String.valueOf(captura4+" "+ captura1+" "+ captura2+" "+ captura3));
      jTextField17.setText(String.valueOf(captura2+" "+ captura3+" "+ captura4+" "+ captura1));
      jTextField18.setText(String.valueOf(captura3+" "+ captura1+" "+ captura2+" "+ captura4));
      jTextField19.setText(String.valueOf(captura2+" "+ captura3+" "+ captura1+" "+ captura4));
      jTextField20.setText(String.valueOf(captura3+" "+ captura1+" "+ captura4+" "+ captura2));
      jTextField21.setText(String.valueOf(captura2+" "+ captura4+" "+ captura3+" "+ captura1));
      jTextField22.setText(String.valueOf(captura3+" "+ captura2+" "+ captura1+" "+ captura4));
      jTextField23.setText(String.valueOf(captura2+" "+ captura4+" "+ captura1+" "+ captura3));
      jTextField24.setText(String.valueOf(captura3+" "+ captura2+" "+ captura4+" "+ captura1));
      jTextField25.setText(String.valueOf(captura2+" "+ captura1+" "+ captura4+" "+ captura3));
      jTextField26.setText(String.valueOf(captura3+" "+ captura4+" "+ captura1+" "+ captura2));
      jTextField27.setText(String.valueOf(captura2+" "+ captura1+" "+ captura3+" "+ captura4));
      jTextField28.setText(String.valueOf(captura3+" "+ captura4+" "+ captura2+" "+ captura1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalNum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
